/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  mainSidebar: [
	  'greetings',
	  {
      type: 'category',
      label: 'VPC',
      items: [
        'vpc-peering/index',
        {type: 'category', label: 'Concepts', items: ['vpc-peering/concepts/index', 'vpc-peering/concepts/connections', 'vpc-peering/concepts/networks']},
        {type: 'category', label:'Step-by-step instructions', items: ['vpc-peering/step-by-step/index', 'vpc-peering/step-by-step/connections', 'vpc-peering/step-by-step/networks']}
      ]/*,
      link: {
        type: 'generated-index',
        title: 'VPC',
        description: 'Manage cloud networks and connect cloud resources',
        slug: '/category/',
        keywords: ['VPC']
      },*/
	}
]
   
};

module.exports = sidebars;
